### ISSUE TITLE
Methold Payment (método de pagamento) erro..

### ISSUE THREAD

**Issue by Amorim2014** [retrocabr/spree_pagarme_payment#1]
Boa noite.....segui o tutorial acima, tudo foi fluindo tranquilamente.
Simulei uma compra, coloquei o endereço e tudo bem, finalizei a entrega e tudo bem.....na terceira etapa (pagamento) surgiu esse erro....

Completed 500 Internal Server Error in 1119ms (ActiveRecord: 6.6ms)

ActionView::Template::Error (undefined local variable or method `pagarme_payment_method' for #<#<Class:0x00000004e3c7c8>:0x007f54555eab90>):
     7:
     8: <%= hidden_field_tag("pagarme_payment", 1) %>
     9: <%= form.fields_for :payments, Spree::Payment.new do |p| %>
    10: <%= p.hidden_field :payment_method_id, :value => pagarme_payment_method.id %>
    11:         <%= p.fields_for :pagarme_payment, p.object.build_pagarme_payment do |pp| %>
    12:                 <%= pp.hidden_field :card_hash %>
    13:                 <%= pp.hidden_field :payment_method %>
  spree_core (3.1.12) app/helpers/spree/base_helper.rb:71:in `method_missing'

Fiz um teste no console dos métodos de pagamento de boleto e cartão está tudo ok.....

CONSOLE
2.3.1 :002 > a.available_methods
 => "boleto,credit_card"
2.3.1 :003 >

não entendi o porque desse erro..podem me ajudar por favor.

Aguardo e obrigado.

**Comment by DekaFugihara** [comment]
Olá Amorim, tudo bom?
Faz muito tempo que não estamos mais trabalhando com essa gem, então desculpe a demora. Mas ficarei feliz em ajudar. :)

Vamos lá. Esse erro é na partial view `app/views/spree/checkout/_payment.html.erb` certo?
Na [linha #3](https://github.com/retrocabr/spree_pagarme_payment/blob/8019624eb5bf82d8116d78110cd43f203f5e377a/app/views/spree/checkout/_payment.html.erb#L3) da partial é definida essa variável `pagarme_payment_method`. A linha ainda está lá? Se você rodar o código
```
Spree::PaymentMethod.find_by_name("Pagar.me")
```
o que ele retorna?

Só para explicar, o `Spree::PaymentMethod` não tem a ver com os meios de pagamentos (boleto, cartão, etc). Ele é uma opção de pagamento (gateway, crédito, etc) configurada no Spree. O código acima deveria retornar o `Spree::PaymentMethod` criado no segundo passo do tutorial, na seção Usage: `Crie um novo Payment Method`. Se você usou outro nome ao criar o método, basta atualizar o nome no código :)

**Comment by Amorim2014** [comment]
Oi Fugihara....o resultado do comando: Spree::PaymentMethod.find_by_name("Pagar.me").....foi esse..

Retorno: 
 Spree::PaymentMethod Load (0.3ms)  SELECT  "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."name" = ? LIMIT 1  [["name", "Pagar.me"]]
 => #<Spree::PaymentMethod::PagarmeMethod id: 4, type: "Spree::PaymentMethod::PagarmeMethod", **name: "Pagar.me"**, description: "Método pagamento do Pagar.me", active: true, deleted_at: nil, created_at: "2017-12-14 16:48:32", updated_at: "2017-12-22 11:00:46", display_on: "both", auto_capture: nil, preferences: {:auto_split=>false, :transfer_fee=>#<BigDecimal:7f80b80b6fe0,'0.0',9(18)>, :use_boleto=>true, :use_credit_cart=>true, :fee_free_bank=>0}, position: 1>
2.3.1 :002 >
IMAGE
![image](https://user-images.githubusercontent.com/6577393/34298095-169d84c6-e703-11e7-8355-8407db021d0d.png)

**Comment by Amorim2014** [comment]
Fugihara.....tirei outro print da tela que continua dando esse erro, acredit que pode ajudar...
![image](https://user-images.githubusercontent.com/6577393/34298203-b58cadc8-e703-11e7-87fa-cdc3f26de041.png)

**Comment by DekaFugihara** [comment]
Desculpe novamente pela demora. Pelo resultado do comando, não há problema para encontrar o Payment Method. Então deve ter alguma questão ao declarar a variável, não sei se é devido à versão do ruby ou alguma outra coisa. Talvez porque a declaração esteja dentro do bloco `<% content_for :head do %>`?
Mas sugiro tentar instanciar a variável antes desse bloco, ou de alguma outra forma, seja pelo controller ou passando como `locals` para a partial.

Também vi que a partial em questão está bem diferente atualmente na aplicação do Spree:
https://github.com/spree/spree/blob/master/frontend/app/views/spree/checkout/_payment.html.erb
Idealmente seria melhor adaptar minha gem atual para a versão atual do Spree, não? :)

**Comment by Amorim2014** [comment]
Boa tarde Denise (Deka) tudo bem......obrigado por responder......esse
projeto do link acima ele está pronto para uso?, qual meio de pagamento ele
tem?...e qual o DB que vc usa....?Caso esteja pronto pensei em usa-lo.

Aguardo retorno.




*Atenciosamente,*

*Carlos A. Amorim*

*+55 046 9914-7819 *






Em 28 de dezembro de 2017 21:53, DekaFugihara <notifications@github.com>
escreveu:
